spring:
  application:
    name: spring-cloud-bus

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

server:
  port: 9000