spring:
  application:
    name: spring-cloud-config-client

  cloud:
    config:
      name: config-bus
  config:
    import: optional:configserver:http://localhost:9000

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

server:
  port: 9001