spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        enabled: true
        git:
          uri: https://github.com/taenypapa/spring-cloud-config.git
          basedir: config


debug: true